### PR TITLE
Changes applied

### PR DESCRIPTION
**Pull request by mengiefen**
- Added blur effect when menu opens
- Readme file modified
- The image overflow has been fixed.

### CODE REVIEW

**Review by rotimiazeez — COMMENTED** [review]
# Hi <STUDENT_MENTION>, 

### While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not meet the project requirement, kindly make sure you meet all the requirements before submitting again

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by mengiefen** [comment]
The previous branch is accidentally merged to base branch. What do you  think I need to do to resolve this situation?

**Comment by julie-ify** [comment]
Hi @mengiefen,

I have checked with the closed branch and saw all the suggested changes from the previous reviewer and that you've implemented all the suggested changes. I'm going to approve this pull request you created but please, do not close PR before it has been approved okay 😉.

Check this [article ](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github)out on how to resolve merge conflict.

**Review by julie-ify — APPROVED** [review]
## Hi @mengiefen, 

# Highlights
- Good job implementing the required changes from the previous reviewer ✔️ 

# Status: Approved ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# Congratulations! 🎉 

Approved emoji

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
